[theme]
base = "dark"
primaryColor = "#00ADB5"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#E0E0E0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
